version: '3.4'
networks:
  scripts_default:  
    external: true
      
services:
  dotnet-agent-portal-gateway:
    build: 
      context: ../
      dockerfile: AgentPortalApiGateway/Dockerfile
    image: dotnet-agent-portal-gateway
    container_name: dotnet-agent-portal-gateway
    ports:
      - "8099:8099"
      - "9000:9000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: 9000
      ASPNETCORE_URLS: ${ASPNETCORE_URLS_API_GATEWAY}
    #   ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
    #   ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_KESTREL_CERTIFICATE_GATEWAY_PATH}
    # volumes:
    #   - ${CERTIFICATE_PATH}:/root/.dotnet/https
    
    
  dotnet-auth-service:
    build: 
      context: ../
      dockerfile: AuthService/Dockerfile
    image: dotnet-auth-service
    container_name: dotnet-auth-service
    ports:
      - "6060:6060"
      - "6061:6061"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: 6061
      ASPNETCORE_URLS: ${ASPNETCORE_URLS_AUTH_SERVICE}
    #   ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
    #   ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
    # volumes:
    #   - ${CERTIFICATE_PATH}:/root/.dotnet/https
      
  
  #dotnet-chat-service:
  #  build: 
  #    context: ../
  #    dockerfile: ChatService/Dockerfile
  #  image: dotnet-chat-service
  #  container_name: dotnet-chat-service
    #network_mode: host

  dotnet-payment-service:
    build: 
      context: ../
      dockerfile: PaymentService/Dockerfile
    image: dotnet-payment-service
    container_name: dotnet-payment-service
    ports:
      - "5070:5070"
      - "5071:5071"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: 5071
      ASPNETCORE_URLS: ${ASPNETCORE_URLS_PAYMENT_SERVICE}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
      

  dotnet-policy-search-service:
    build: 
      context: ../
      dockerfile: PolicySearchService/Dockerfile
    image: dotnet-policy-search-service
    container_name: dotnet-policy-search-service
    ports:
      - "5060:5060"
      - "5061:5061"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: 5061
      ASPNETCORE_URLS: ${ASPNETCORE_URLS_POLICYSEARCH_SERVICE}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
      

  dotnet-policy-service:
    build: 
      context: ../
      dockerfile: PolicyService/Dockerfile
    image: dotnet-policy-service
    container_name: dotnet-policy-service
    ports:
      - "5050:5050"
      - "5051:5051"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: 5051
      ASPNETCORE_URLS: ${ASPNETCORE_URLS_POLICY_SERVICE}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
      

  dotnet-pricing-service:
    build: 
      context: ../
      dockerfile: PricingService/Dockerfile
    image: dotnet-pricing-service
    container_name: dotnet-pricing-service
    ports:
      - "5040:5040"
      - "5041:5041"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: 5041
      ASPNETCORE_URLS: ${ASPNETCORE_URLS_PRICING_SERVICE}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
   
  

  dotnet-product-service:
    build: 
      context: ../
      dockerfile: ProductService/Dockerfile
    image: dotnet-product-service
    container_name: dotnet-product-service
    ports:
      - "5030:5030"
      - "5031:5031"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: 5031
      ASPNETCORE_URLS: ${ASPNETCORE_URLS_PRODUCT_SERVICE}
      #ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      #ASPNETCORE_Kestrel__Certificates__Default__Path: /root/.dotnet/https/myTLS.pfx
    #volumes:
    #  - C:\tmp\certs\:/root/.dotnet/https
    # networks:
    #   - scripts_default
  

      
  #dotnet-web-vue:
  #  build: ../Web
  #  image: dotnet-web-vue
  #  container_name: dotnet-web-vue
    #network_mode: host